name:                prettyprinter-ansi-sgr
version:             0.1.0.0
github:              "reixn/prettyprinter-ansi-sgr"
license:             BSD3
author:              "reixn"
maintainer:          "reixn@outlook.com"
copyright:           "2022 reixn"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Text, User Interfaces

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/reixn/prettyprinter-ansi-sgr#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal
- prettyprinter >= 1.7.0
- text >= 1.2
- semigroups >= 0.1

other-extensions:
- OverloadedStrings

library:
  source-dirs: src
